### PR TITLE
a "skipBaselineComparison" flag to... skip baseline comparison

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
@dgolovin @nickboldt @maxandersen here is the flag!

**Comment by nickboldt** [comment]
What about having a new parameter within the mojo itself, so we could do -Dcompare-version-with-baselines.skip on any build that uses the mojo?

**Comment by mickaelistria** [comment]
the mojo is about to move to Tycho, and the Tycho team doesn't like to add immediately command-line flags for parameters at 1st release, since they are likely to change with its first bunch of users reporting feedback.

**Comment by nickboldt** [comment]
OK, then +1 for this, if @dgolovin likes the name of the variable.

**Comment by nickboldt** [comment]
btw, the reason that portlet fails the version validation check is that people have changed it in master branch since 4.2.x

    https://github.com/jbosstools/jbosstools-portlet/commits/master

    so... either you should just check out the 4.2.x branch to do your "everything in a single build" build, or we should *actually upversion the sources in master* to use a newer version

    see, the baseline check here is actually failing CORRECTLY :D

**Comment by dgolovin** [comment]
Fire a JIRA for portlet then.

**Comment by dgolovin** [comment]
This PR works for me.
Thanks!

**Comment by nickboldt** [comment]
JIRA for portlet versioning problem: https://issues.jboss.org/browse/JBIDE-20025

**Comment by maxandersen** [comment]
there are multiple things one could do with baselines (api check, version check, etc) - how about making this more specific: `skipVersionBumpCheck` ? (wether it is against a base line or not is not really relevant)

**Pull request merged**
