### PR TITLE
JBIDE-23206 because this is useful for...

### PR DESCRIPTION
**Pull request by nickboldt**
JBIDE-23206 because this is useful for building PRs locally to test 'em, I suggest we call the profile R so that the flag to activate this build mode is simply '-PR'

### CODE REVIEW

**Comment by mickaelistria** [comment]
Could also be enable by a property `ontUseGitTimestamps` so it would be triggered by `-DontUseGitTimestamps` ;)

**Comment by nickboldt** [comment]
Sure, or -DefaultTimestamps. But isn't -PR simpler? :D

**Comment by jeffmaury** [comment]
+1 but you can have both a R profile and a property to activate it, no ?

**Comment by nickboldt** [comment]
Yes, the profile could be enabled when a property contains a specific value. Which property would you like? Which value? Please be specific.

**Comment by jeffmaury** [comment]
I'm ok with dontUseGitTimestamps

**Comment by nickboldt** [comment]
If you mean creating a property ontUseGitTimestamps, which is invoked with -DontUseGitTmeStamps, I can make that happen. But what's the value add here, vs. just using -PR? Is it because you like to type longer commands when building? :D

**Pull request merged**
