### PR TITLE
JBIDE-26644 Update jacoco plugin to 0.8.4 and sonar maven plugin to

### PR DESCRIPTION
**Pull request by jkopriva**
3.6.0.1398

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
@jeffmaury can you please review? Thank you!

**Comment by jeffmaury** [comment]
The only concern I have is that our master builds then run an Ant task to generate HTML reports from the jacoco exec file and this is not working with Jacoco 0.8.x but if Sonar provides the code coverage I think we can remove that step

**Comment by jkopriva** [comment]
I have PR in openshift: https://github.com/jbosstools/jbosstools-openshift/pull/1845 for code coverage on sonarcloud.io: https://sonarcloud.io/dashboard?id=jbosstools_jbosstools-openshift

**Comment by jkopriva** [comment]
@jeffmaury In which job is ant task? Thank you!

**Comment by jeffmaury** [comment]
Every master job is running Ant to process Jacoco files after the maven build is finished.

**Comment by jkopriva** [comment]
@jeffmaury Hi, I can see it is processed by ant, but afterwards I have not found where are any results from this processed/used, so maybe we should consider removing this ant task and use sonarcloud instead. WDYT?
cc: @robstryker @sbouchet @odockal

**Comment by odockal** [comment]
I am definitely not against the idea of moving from ant task to maven plugin. +1

**Comment by sbouchet** [comment]
Same for me, as we already have some sonarcloud, let's move on it and get rid of old ant tasks. +1

**Comment by adietish** [comment]
Sounds like a good idea to me. But somehow this went forgotten, I'd love to get this merged once 4.13.0.Final is released

**Comment by jkopriva** [comment]
@adietish yes!, I will update PRs after GA is out.

**Comment by sbouchet** [comment]
@adietish : agreed ! +1

**Comment by jkopriva** [comment]
@sbouchet @jeffmaury  Hi, can you please review? Thank you!

**Pull request merged**
