### PR TITLE
move repository-utils to pluginManagement >> master

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by mickaelistria** [comment]
-1
If we use pluginManagement, we only define configuration, and children poms that actually need these features need add the few lines to invoke the plugins. Since we really want to enforce which plugins are actually run and we want to avoid tweaking all site/pom.xml, it's IMO better to keep using plugins instead of pluginManagement.

**Comment by maxandersen** [comment]
@mickaelistria this patch does not move everything to pluginManagement, it is still activated in the plugin section.

Looking at what is repeated in integrationstack then I'm really wondering why we have to duplicate about 80% of what is already in parent pom anyways - if the plugin version does not need repeating why is majority of the configuration not possible to remove too ?  integrationstack should just have to list its associate sites right ? everything else would be inherited.

**Comment by mickaelistria** [comment]
> this patch does not move everything to pluginManagement, it is still activated in the plugin section.

Ok, so overall, this patch won't change anything IMO.

> Looking at what is repeated in integrationstack then I'm really wondering why we have to duplicate about 80% of what is already in parent pom anyways - if the plugin version does not need repeating why is majority of the configuration not possible to remove too ? integrationstack should just have to list its associate sites right ? everything else would be inherited.

+1.
I don't think the issue is in the parent pom. It's more the consumers of the parent pom who don't make clean usage of Maven inheritance mechansim.

**Comment by nickboldt** [comment]
Rejected.

**Pull request closed without merging**
