### PR TITLE
JBIDE-26336 - upgrade jacoco from 0.8.1 to 0.8.2 for Java 11 profile

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
I upgraded only for JDK 11 profile as it was done like that before but for future why not upgrading for all profiles?

**Comment by jeffmaury** [comment]
Because those new versions are not compatible with some Jenkins plugins

**Comment by apupier** [comment]
> Because those new versions are not compatible with some Jenkins plugins

is it due to JaCoCo plugin? https://wiki.jenkins.io/display/JENKINS/JaCoCo+Plugin#JaCoCoPlugin-OpenTickets(bugsandfeaturerequests)
If yes, it seems a new version has been released. version will need to be updated at the same time on jenkins and in the projects :s 

anyway, we are in code freeze and it will be merged in a week, right?

**Comment by jeffmaury** [comment]
Yes

**Pull request merged**
